## ------------ Options -------------
loadSize : 120
fineSize : 320    ## 最终输入网络的图片尺寸
patchSize : 32    ## 局部判别器 patch 尺寸
batchSize : 8    ## 
test_dataroot : ./test_dataset
train_dataroot : /mnt3/changruowang/data/EnlightGanData
name : single_gan_train
model : single
dataset_mode : unaligned
which_model_netG : sid_unet_resize
which_model_netD : no_norm_4
patchD : True
patch_vgg : True
patchD_3 : 5
n_layers_D : 5
n_layers_patchD : 4
use_norm : 1
use_wgan : 0
use_ragan : True
hybrid_loss : True
times_residual : True
instance_norm : 0
vgg : 1
vgg_choose : relu5_1
no_dropout : True
skip : 1
self_attention : True
